### PR TITLE
Update to goss 0.3.10

### PR DESCRIPTION
**Pull request by matrixise**

### CODE REVIEW

**Comment by ssbarnea** [comment]
You will need to wait for me to finish migrating it to be a v3 plugin and setting up Zuul CI. I just finished doing that for molecule-vagrant and started with goss.

**Comment by ssbarnea** [comment]
please rebase

**Comment by matrixise** [comment]
Rebased to master, please wait and see.

**Comment by ssbarnea** [comment]
We already have newer version

**Pull request closed without merging**
